### ISSUE TITLE
Result after upload

### ISSUE THREAD

**Issue by kilik128** [cdgco/dream-api#2]
Any idea why we got not the same result when Input Image on web site ?
when use api is look give like unfinished result 
thank's for info

**Comment by cdgco** [comment]
Firstly, it looks like Wombo has changed how the internal API works so this package is currently broken but will be updated today. As for the difference in pictures, I can't really tell without more detail. From my tests, everything is working as expected with minor variation as expected from the AI. Please check to make sure all variables are set as expected including the prompt, input image, style and influence level. Also make sure to use the final.jpg result image and not one of the intermediate images. Finally, note that this tool does not put a watermark on the image like the web version does, so there will be no frame around the final image, this is expected behaviour.

For reference, this is the code I am using to test:
```
const WomboDream = require('dream-api');
const fs = require('fs');
let buffer = fs.readFileSync('./test.jpg');
WomboDream.generateImage(3, "dog", null, buffer).then((image) => {
    console.log(image);
});
```

**Comment by cdgco** [comment]
v1.0.8 has been published on NPM and GitHub NPM

**Comment by kilik128** [comment]
thank's i will check that's 
it's possible i miss somethink's in script







![chrome_2022-07-25_20-45-02](https://user-images.githubusercontent.com/8617095/180851550-b49f7d58-eb0a-4c58-a9e6-0258f61d4496.jpg)

![chrome_2022-07-25_20-44-58](https://user-images.githubusercontent.com/8617095/180851584-34aca95e-5170-4c38-807e-248c61562e1a.jpg)


```


var Prompt = "wool";
var Style = 0;
var Weigth =  "HIGH"	;//  "LOW" "MEDIUM" "HIGH"
var Path_Import = String.raw`V:\Generation\Movie\01`;
var Path_Export = String.raw`V:\Generation\Movie\02`;
var Frequency = 10;
var Img = true;

const { buildDefaultInstance } = require('wombo-dream-api');
const fs = require('fs');
const https = require("https");
var files = fs.readdirSync(Path_Import ); // './Craft/'
//console.log(files);
files = shuffle(files );


function shuffle(array ) {
  let currentIndex = array.length,  randomIndex;

  // While there remain elements to shuffle.
  while (currentIndex != 0) {

    // Pick a remaining element.
    randomIndex = Math.floor(Math.random() * currentIndex);
    currentIndex--;

    // And swap it with the current element.
    [array[currentIndex], array[randomIndex]] = [
      array[randomIndex], array[currentIndex]];
  }

  return array;
}


//goonous
(async () => {
	try {
		const credentials = {
			email: '@.com',
			password: '',
		};

		// signin is automatically done when you interract with the api if you pass credentials
		const wombo = buildDefaultInstance(credentials);

		// if you want to sign up as new user:
		// await wombo.authentifier.signUp(credentials);

		// fetch all styles
		const styles = await wombo.fetchStyles();
		console.log(styles.map((style) => `[${style.id}] ${style.name}`));



		for (const filename of files) { 
		//for (let i = 0; i < 1000; i++) {
 		//await delay(2500);

		console.log(filename );

		// upload image [ONLY JPEG SUPPORTED]
		const uploadedImage = await wombo.uploadImage(
			fs.readFileSync(Path_Import +"/"+ filename)
			//fs.readFileSync('./image.jpeg')
		);

		
 	

		// generate picture from image
		const generatedTask = await wombo.generatePicture(
			Prompt ,
			styles[Style ].id,
			(taskInProgress) => {
				console.log(
					`[${taskInProgress.id}]: ${taskInProgress.state} | step: ${taskInProgress.photo_url_list.length}`
				);
			},
			{mediastore_id: uploadedImage.id,  weight: Weigth ,frequency: Frequency  } //

			);


		console.log(
			`[${generatedTask.id}]: ${generatedTask.state} | final url: ${generatedTask.result?.final}`
		);

	    // to interract with the gallery, YOU NEED TO HAVE A USERNAME!
	    // if you just created the account and it doesn't have a username, set it with:
	    // await wombo.setUsername('myusername');

	    // save an image in the gallery
		const savedTask = await wombo.saveTaskToGallery(
			generatedTask.id,
			'my wonderful creation',
			true,
			true
		);

		console.log('image saved!');

		// URL of the image
                const url = generatedTask.result?.final;

https.get(url, (res) => {
  const path = Path_Export + "/" + filename  + generatedTask.id+".jpeg";
  const writeStream = fs.createWriteStream(path);

  res.pipe(writeStream);

  writeStream.on("finish", () => {
    writeStream.close();
    console.log("Download Completed");
  });
});

}




		// obtain gallery tasks
		const galleryTasks = await wombo.fetchGalleryTasks();

		//console.log(galleryTasks);
	} catch (error) {
		console.error(error);
	}
})();




















```

**Comment by cdgco** [comment]
I think you are using a different package. This package is `dream-api` not `wombo-dream-api`. If you're intending to use `wombo-dream-api` that can be found here https://github.com/leopoldhub/wombo-dream-api by a different developer. If you meant to use this package, please see the examples in the examples folder.

**Comment by kilik128** [comment]
Oh i see sorry for the misstake ! 
ok cool i will try this one thank's

**Comment by kilik128** [comment]
i have try this

`const WomboDream = require('dream-api');
const fs = require('fs');
let buffer = fs.readFileSync('./test.jpg');
WomboDream.generateImage(3, "dog", null, buffer).then((image) => {
    console.log(image);
});`

and result 
![final (4)](https://user-images.githubusercontent.com/8617095/180856614-a5add028-d563-4cdb-a0ef-88edea6a5dc7.jpg)
