### ISSUE TITLE
CORS error on post request

### ISSUE THREAD

**Issue by eyubkh** [cdgco/dream-api#3]
I'm trying to use the api but when it does the post requests I'm getting CORS errors, some idea that what can be happening?
pd: I love your api and how you have build it 

![Screenshot 2022-10-04 at 12 09 59](https://user-images.githubusercontent.com/66533853/193804332-f99344e7-0f2f-4f6f-ae77-2931459e04d7.png)

**Comment by cdgco** [comment]
Sorry I missed this. Are you trying to run the API in a frontend client or something similar? If I remember correctly, Wombo has some restrictions in place that prevent requests from being sent from client sessions, so you must run the API server side.

I can't remember the exact details, but I tried compiling this package down to a frontend script but these CORS limitations prevented me from doing so.

**Comment by vbhakta8** [comment]
FYI y'all could just use our public API where you aren't breaking our terms of service, it's also free [api.dream.ai](https://api.dream.ai) 😬

**Comment by bjshumway** [comment]
@vbhakta8 

Oh, I see I have been using the API mentinoed at your website: https://api.dream.ai/

Which has the endpoint....

https://api.luan.tools/api/tasks/

However, this "dream-api" github repo goes against

https://paint.api.wombo.ai/api/v2/tasks/

Is that the non-public (private) endpoint it's hitting? That's breaking terms of service?

Also... my experience going against the "api.luan.tools" endpoint has been dreadful. I followed the API guide and my images are coming out looking broken and confused. What am I missing?

**Comment by cdgco** [comment]
I'm happy to build a new module or adapt this module to support the new official API now that it's available, but this package was built before it was available and is not meant to be used with the new version that supports height and width. This isn't the place to ask for help with that, I would recommend asking on the Wombo discord https://discord.com/invite/wombo.
